name: Check Typos

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-typos:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: AutoCorrect
      uses: huacnlee/autocorrect-action@v2

    - name: typos-action
      uses: crate-ci/typos@v1.31.1